SELECT B.ID BRANCH_ID, B.NAME BRANCH_NAME, IFNULL(SUM(A.COUNT), 0) COUNT
FROM BRANCHES B
    LEFT OUTER JOIN (
    SELECT BRANCH_ID, SUM(S.COUNT) COUNT
    FROM EMPLOYEES E
    JOIN (
    SELECT EMPLOYEE_ID, COUNT(*) COUNT
    FROM SELLINGS
    WHERE CAR_ID=306
    GROUP BY EMPLOYEE_ID
    ) S ON E.ID = S.EMPLOYEE_ID
    GROUP BY BRANCH_ID
    ) A
ON A.BRANCH_ID = B.ID
GROUP BY B.ID
ORDER BY B.ID
