SELECT CP.CART_ID AS CART_ID,
       IF(CP.SUM >= C.MINIMUM_REQUIREMENT, 0, 1) AS ABUSED
FROM (
         SELECT ID, CART_ID, SUM(PRICE) AS SUM
         FROM CART_PRODUCTS
         GROUP BY CART_ID
     ) AS CP
         JOIN COUPONS AS C
              ON CP.CART_ID = C.CART_ID
GROUP BY CP.CART_ID
ORDER BY CP.ID